// Turns the exported n8n spreadsheet into an idempotent SQL import.
//
//   node scripts/import-history.mjs "C:/Users/Admin/Downloads/Airbnb Bookings.csv"
//
// Writes supabase/migrations/20260725000100_import_history.sql. It refuses to emit anything
// if the history contains two overlapping confirmed or blocked stays on one unit, because
// the exclusion constraint would reject the whole file anyway — better to be told which two
// rows are the problem than to read a constraint violation.

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const csvPath = process.argv[2];
if (!csvPath) { console.error('Usage: node scripts/import-history.mjs <path-to-csv>'); process.exit(1); }

// The sheet quotes any field containing a comma — "Brañanola, Agatha Mei M." — so the rows
// cannot be split naively.
function parseCsv(text) {
  const rows = [];
  let row = [], field = '', quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') quoted = false;
      else field += c;
    } else if (c === '"') quoted = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c !== '\r') field += c;
  }
  if (field || row.length) { row.push(field); rows.push(row); }
  return rows;
}

// The export carries a UTF-8 BOM, which would otherwise become part of the first column's
// name and silently turn every booking_id into null.
const rows = parseCsv(readFileSync(csvPath, 'utf8').replace(/^﻿/, ''));
const header = rows[0];

if (header[0] !== 'booking_id') {
  console.error(`Unexpected first column "${header[0]}" — expected booking_id.`);
  process.exit(1);
}
const col = name => header.indexOf(name);
const records = rows.slice(1)
  .filter(r => r.length > 1 && r[0])
  .map(r => Object.fromEntries(header.map((h, i) => [h, (r[i] ?? '').trim()])));

// 'inquiry' was the old system's name for a form submission that never paid. In the new
// schema that is awaiting_payment: it holds no dates and is owed nothing.
const STATUS = { blocked: 'blocked', confirmed: 'confirmed', inquiry: 'awaiting_payment' };

const unknown = [...new Set(records.map(r => r.status).filter(s => !STATUS[s]))];
if (unknown.length) {
  console.error(`Unmapped status values: ${unknown.join(', ')}`);
  process.exit(1);
}

// ---------------------------------------------------------------- overlap check
// Only confirmed and blocked rows close dates, so only they can collide. Holds are meant
// to overlap and are excluded from the constraint.
const closing = records
  .filter(r => ['confirmed', 'blocked'].includes(r.status))
  .map(r => ({ id: r.booking_id, unit: r.unit, ci: r.check_in, co: r.check_out, who: r.guest_name }));

const clashes = [];
for (let i = 0; i < closing.length; i++) {
  for (let j = i + 1; j < closing.length; j++) {
    const a = closing[i], b = closing[j];
    // Half-open: check_out === other check_in is same-day turnover, not a clash.
    if (a.unit === b.unit && a.ci < b.co && a.co > b.ci) clashes.push([a, b]);
  }
}

if (clashes.length) {
  console.error(`\n${clashes.length} overlapping stay(s) in the history — nothing written:\n`);
  for (const [a, b] of clashes) {
    console.error(`  ${a.unit}  ${a.id} ${a.who} ${a.ci}→${a.co}`);
    console.error(`        overlaps ${b.id} ${b.who} ${b.ci}→${b.co}\n`);
  }
  console.error('Decide which one actually happened, fix the CSV, and re-run.');
  process.exit(1);
}

// ---------------------------------------------------------------- emit
const q = v => (v === '' || v == null) ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const qn = v => (v === '' || v == null) ? 'null' : String(Number(v));

const values = records.map(r => {
  const status = STATUS[r.status];
  return '  (' + [
    q(r.booking_id),
    q(r.unit),
    q(r.check_in),
    q(r.check_out),
    `${q(status)}::booking_status`,
    q(r.guest_name),
    q(r.fb_name),
    q(r.email ? r.email.toLowerCase() : ''),
    q(r.mobile),
    // Manual blocks carry no guest count; the column is NOT NULL with a >= 1 check.
    r.guests === '' ? '1' : qn(r.guests),
    q(r.payment_ref),
    q(r.confirmed_by),
    q(r.confirmed_at),
    q(r.paid_at),
    q(r.notes),
  ].join(', ') + ')';
});

const counts = records.reduce((a, r) => (a[STATUS[r.status]] = (a[STATUS[r.status]] || 0) + 1, a), {});

const sql = `-- Historical bookings imported from the n8n spreadsheet export.
--
-- Generated by scripts/import-history.mjs — do not hand-edit; re-run the script instead.
-- Source rows: ${records.length} (${Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(', ')}).
--
-- The old 'inquiry' status became awaiting_payment: a form submission that never paid holds
-- no dates and is owed nothing. Those rows are hidden from the admin list by design, but are
-- kept so the history stays intact.
--
-- Original booking ids (BK-nnn / BLK-nnn) are preserved. Guests have these references from
-- emails and Messenger threads, and new bookings use the SK-XXXXXX format, so the two cannot
-- collide.

begin;

-- Importing would otherwise queue a "your dates are waiting" email to every one of the
-- ${counts.awaiting_payment ?? 0} inquiry rows — real addresses, for bookings abandoned weeks ago.
alter table bookings disable trigger booking_emails;

insert into bookings (
  booking_id, unit, check_in, check_out, status,
  guest_name, fb_name, email, mobile, guests,
  payment_ref, confirmed_by, confirmed_at, paid_at, notes
) values
${values.join(',\n')}
on conflict (booking_id) do nothing;

alter table bookings enable trigger booking_emails;

commit;

-- Expect ${records.length} rows, of which ${(counts.confirmed ?? 0) + (counts.blocked ?? 0)} close dates.
select status, count(*) from bookings group by status order by status;
`;

const out = join(root, 'supabase', 'migrations', '20260725000100_import_history.sql');
writeFileSync(out, sql);

console.log(`No overlapping stays in the history — safe to import.\n`);
console.log(`  ${records.length} rows: ${Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(', ')}`);
console.log(`\nWrote supabase/migrations/20260725000100_import_history.sql`);
