-- Historical bookings imported from the n8n spreadsheet export.
--
-- Generated by scripts/import-history.mjs — do not hand-edit; re-run the script instead.
-- Source rows: 37 (11 blocked, 19 awaiting_payment, 7 confirmed).
--
-- The old 'inquiry' status became awaiting_payment: a form submission that never paid holds
-- no dates and is owed nothing. Those rows are hidden from the admin list by design, but are
-- kept so the history stays intact.
--
-- Original booking ids (BK-nnn / BLK-nnn) are preserved. Guests have these references from
-- emails and Messenger threads, and new bookings use the SK-XXXXXX format, so the two cannot
-- collide.

begin;

-- Importing would otherwise queue a "your dates are waiting" email to every one of the
-- 19 inquiry rows — real addresses, for bookings abandoned weeks ago.
alter table bookings disable trigger booking_emails;

insert into bookings (
  booking_id, unit, check_in, check_out, status,
  guest_name, fb_name, email, mobile, guests,
  payment_ref, confirmed_by, confirmed_at, paid_at, notes
) values
  ('BLK-181', 'B301', '2026-07-01', '2026-07-13', 'blocked'::booking_status, 'Manual block', null, null, null, 1, null, null, null, null, 'Other'),
  ('BLK-182', 'B305', '2026-07-01', '2026-07-13', 'blocked'::booking_status, 'Manual block', null, null, null, 1, null, null, null, null, 'Personal use'),
  ('BLK-185', 'B305', '2026-08-11', '2026-08-17', 'blocked'::booking_status, 'Bash booking', null, null, null, 1, null, null, null, null, 'Direct booking'),
  ('BLK-187', 'B305', '2026-07-13', '2026-07-14', 'blocked'::booking_status, 'Pest control', null, null, null, 1, null, null, null, null, 'Maintenance'),
  ('BLK-188', 'B305', '2026-07-14', '2026-07-15', 'blocked'::booking_status, 'Pest control', null, null, null, 1, null, null, null, null, 'Personal use'),
  ('BLK-219', 'B301', '2026-07-13', '2026-07-14', 'blocked'::booking_status, 'Bash', null, null, null, 1, null, null, null, null, 'Direct booking'),
  ('BK-238', 'B305', '2026-07-25', '2026-07-26', 'awaiting_payment'::booking_status, 'Lady Lyn Ochea', 'Lady Lyn Ochea', 'ladylynochea@gmail.com', '09515819171', 2, null, null, null, null, null),
  ('BK-242', 'B305', '2026-07-25', '2026-07-26', 'confirmed'::booking_status, 'Lady Lyn Ochea', 'Lady Lyn Ochea', 'ladylynochea@gmail.com', '09515819171', 2, '621767', 'Owner', '2026-07-13T22:14:24.608+08:00', '2026-07-13T22:11:04.490+08:00', null),
  ('BK-251', 'B301', '2026-07-14', '2026-07-15', 'confirmed'::booking_status, 'Chai Chu', 'Chai Chu', 'gelerajoanamae@gmail.com', '09657020042', 2, '4042856836768', 'Owner', '2026-07-13T22:38:54.521+08:00', '2026-07-13T22:37:10.577+08:00', null),
  ('BK-264', 'B305', '2026-07-18', '2026-07-19', 'awaiting_payment'::booking_status, 'Chenvy Marie Pejante', 'Chenvy Marie Pejante', 'sinbipejante@gmail.com', '09772840930', 2, null, null, null, null, null),
  ('BK-267', 'B305', '2026-07-18', '2026-07-19', 'awaiting_payment'::booking_status, 'Chenvy Marie Pejante', 'Chenvy Marie Pejante', 'sinbipejante@gmail.com', '+639772840930', 2, null, null, null, null, null),
  ('BK-270', 'B305', '2026-07-18', '2026-07-19', 'awaiting_payment'::booking_status, 'Chenvy Marie Pejante', 'Chenvy Marie Pejante', 'sinbipejante@gmail.com', '+639772840930', 2, null, null, null, null, null),
  ('BLK-288', 'B305', '2026-07-18', '2026-07-19', 'blocked'::booking_status, 'Bash', null, null, null, 1, null, null, null, null, 'Direct booking'),
  ('BLK-291', 'B301', '2026-07-17', '2026-07-18', 'blocked'::booking_status, 'Myth', null, null, null, 1, null, null, null, null, 'Direct booking'),
  ('BLK-296', 'B301', '2026-07-15', '2026-07-16', 'blocked'::booking_status, 'Manual block', null, null, null, 1, null, null, null, null, 'Maintenance'),
  ('BLK-297', 'B305', '2026-07-15', '2026-07-16', 'blocked'::booking_status, 'Manual block', null, null, null, 1, null, null, null, null, 'Maintenance'),
  ('BK-341', 'B301', '2026-07-18', '2026-07-19', 'awaiting_payment'::booking_status, 'Trisha Amores', 'Trisha Amores', 'jennyrivera070558@gmail.com', '09217437736', 9, null, null, null, null, null),
  ('BK-344', 'B301', '2026-07-18', '2026-07-19', 'confirmed'::booking_status, 'Trisha Amores', 'Trisha Amores', 'jennyrivera070558@gmail.com', '09217437736', 9, '09774417298', 'Owner', '2026-07-17T13:52:34.383+08:00', '2026-07-17T13:13:43.299+08:00', null),
  ('BK-354', 'B305', '2026-07-23', '2026-07-24', 'awaiting_payment'::booking_status, 'Petpet Alberto', 'Petpet Alberto', 'wilbby.alberto@gmail.com', '09694248685', 2, null, null, null, null, null),
  ('BK-361', 'B305', '2026-07-23', '2026-07-24', 'awaiting_payment'::booking_status, 'Petpet Alberto', 'Petpet Alberto', 'wilbby.alberto@gmail.com', '09694248685', 2, null, null, null, null, null),
  ('BK-365', 'B305', '2026-07-23', '2026-07-24', 'awaiting_payment'::booking_status, 'Petpet Alberto', 'Petpet Alberto', 'wilbby.alberto@gmail.com', '09694248685', 2, null, null, null, null, null),
  ('BK-368', 'B305', '2026-07-23', '2026-07-24', 'awaiting_payment'::booking_status, 'Petpet Alberto', 'Petpet Alberto', 'wilbby.alberto@gmail.com', '09694248685', 2, null, null, null, null, null),
  ('BK-371', 'B305', '2026-07-23', '2026-07-24', 'confirmed'::booking_status, 'Petpet Alberto', 'Petpet Alberto', 'wilbby.alberto@gmail.com', '09694248685', 2, '2043003237371', 'Owner', '2026-07-17T22:42:42.381+08:00', '2026-07-17T22:39:34.919+08:00', null),
  ('BK-410', 'B305', '2026-07-21', '2026-07-22', 'awaiting_payment'::booking_status, 'Harry Lopez', 'Harry Lopez', 'lopezharry196@gmail.com', '9264600533', 2, null, null, null, null, null),
  ('BK-413', 'B305', '2026-07-21', '2026-07-22', 'awaiting_payment'::booking_status, 'Harry Lopez', 'Harry Lopez', 'lopezharry196@gmail.com', '9264600533', 2, null, null, null, null, null),
  ('BK-416', 'B305', '2026-07-21', '2026-07-22', 'awaiting_payment'::booking_status, 'Harry Lopez', 'Harry Lopez', 'lopezharry196@gmail.com', '092646000533', 2, null, null, null, null, null),
  ('BK-419', 'B305', '2026-07-21', '2026-07-22', 'awaiting_payment'::booking_status, 'Harry Lopez', 'Harry Lopez', 'lopezharry196@gmail.com', '09264600533', 2, null, null, null, null, null),
  ('BK-422', 'B305', '2026-07-21', '2026-07-22', 'confirmed'::booking_status, 'Harry Lopez', 'Harry Lopez', 'lopezharry196@gmail.com', '09264600533', 2, '3043104400350', 'Owner', '2026-07-20T23:23:26.010+08:00', '2026-07-20T21:45:47.385+08:00', null),
  ('BK-477', 'B301', '2026-07-25', '2026-07-26', 'awaiting_payment'::booking_status, 'Deib abalos', 'Deib abalos', 'debbieabalos4@gmail.com', '09687071416', 2, null, null, null, null, null),
  ('BK-479', 'B305', '2026-07-26', '2026-07-27', 'confirmed'::booking_status, 'Andre Gentalian lataza', 'Andre Gentalian lataza', 'andregentilian@gmail.com', '09930431412', 2, '9043168888655', 'Owner', '2026-07-22T20:09:31.463+08:00', '2026-07-22T20:08:52.771+08:00', null),
  ('BK-491', 'B305', '2026-08-07', '2026-08-10', 'awaiting_payment'::booking_status, 'Novie Claire Maquilang', 'Novie Claire Maquilang', 'novieclaire23@gmail.com', '09760826499', 2, null, null, null, null, null),
  ('BK-494', 'B305', '2026-08-07', '2026-08-10', 'confirmed'::booking_status, 'Novie Claire Maquilang', 'Novie Claire Maquilang', 'novieclaire23@gmail.com', '09760826499', 2, 'UB839140', 'Owner', '2026-07-22T21:20:41.821+08:00', '2026-07-22T21:18:55.731+08:00', null),
  ('BK-503', 'B301', '2026-08-20', '2026-08-25', 'awaiting_payment'::booking_status, 'Devadarshan', 'Devadarshan', 'devadarshanthyagarajan@gmail.com', '09763169232', 2, null, null, null, null, null),
  ('BLK-509', 'B301', '2026-07-25', '2026-07-26', 'blocked'::booking_status, 'Manual block', null, null, null, 1, null, null, null, null, 'Personal use'),
  ('BK-537', 'B305', '2026-07-24', '2026-07-25', 'awaiting_payment'::booking_status, 'Brañanola, Agatha Mei M.', 'Brañanola, Agatha Mei M.', 'agathamenoria16@gmail.com', '0995916424', 3, null, null, null, null, null),
  ('BK-539', 'B305', '2026-07-24', '2026-07-25', 'awaiting_payment'::booking_status, 'Brañanola, Agatha Mei M.', 'Brañanola, Agatha Mei M.', 'agathamenoria16@gmail.com', '0995916424', 4, null, null, null, null, null),
  ('BK-565', 'B305', '2026-08-03', '2026-08-04', 'awaiting_payment'::booking_status, 'Mitch Aya Llanto', 'Mitch Aya Llanto', 'mitchayadanollanto@gmail.com', '09668179364', 2, null, null, null, null, null)
on conflict (booking_id) do nothing;

alter table bookings enable trigger booking_emails;

commit;

-- Expect 37 rows, of which 18 close dates.
select status, count(*) from bookings group by status order by status;
